app:
  auth:
    accessTokenSecret: ${ACCESS_TOKEN_SECRET}
    refreshTokenSecret: ${REFRESH_TOKEN_SECRET}
    accessTokenExpiry: 86400000
    refreshTokenExpiry: 604800000
    refreshTokenNearExpiryCriterion: 259200000

jwt:
  token:
    secret-key: [secret-key]
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000