spring:
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: application-datasource.yml, application-auth.yml, application-oauth.yml